### ISSUE TITLE
Erreur mauvaise coloration syntaxique Java après un //

### ISSUE THREAD

**Issue by Sylvain-Bugat** [AntSoft/openChat#23]
La coloration syntaxique d'un bout de code en Java met en tout en commentaire après le premier // indiquant normalement un commentaire sur une ligne. Il doit le confondre avec un /\* qui indique effectivement le début d'un bloc de commentaire sur plusieurs lignes.
A voir s'il faut remonter le bug au module de coloration syntaxique utilisé.

**Comment by lpaolotti** [comment]
Exemple : 

sur le code java 

``` java
private int toto = 4; //YESSS

public void run(){
}
```

La signature et le corps de la methode run() sont detectés en tant que commentaire car on envoie le code suivant a la librairie :

``` html
<pre>
<code class="hljs">private int toto = 4; //YESSS<div><br></div><div>public void run(){</div><div></div> 
</code>
</pre>
```

Il y a du html qui est inséré dans le code Java, ce qui implique que le parsing ne se passe pas bien.

**Comment by lpaolotti** [comment]
Corrigé en 87e6e92cb892abab0886b8378458bef4d32ee10f

**Comment by Sylvain-Bugat** [comment]
Cool merci!
